name: Publish Python Package

on:
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    # Шаг 1. Проверяем код из репозитория
    - name: Checkout code
      uses: actions/checkout@v3

    # Шаг 2. Устанавливаем Python и зависимости
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install build twine

    # Шаг 3. Собираем дистрибутив
    - name: Build the package
      run: python -m build

    # Шаг 4. Публикуем на PyPI
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__ # Пользователь для токенов PyPI
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }} # Токен из Secrets
      run: python -m twine upload dist/*
