name: Publish Python Package
on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  publish:
    environment: release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
      - uses: actions/checkout@c7d749a2d57b4b375d1ebcd17cfbfb60c676f18e
