name: Publish Python Package

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
