name: Publish Python Package
on:
  push:
    branches:
      - main

permissions:
  contents: none

jobs:
  publish:
    environment: release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
