name: Log Issue Content

on:
  issues:
    types: [opened]

jobs:
  log-issue-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print issue content
        env:
          TITLE: ${{ github.event.issue.title }}
          BODY: ${{ github.event.issue.body }}
        run: |
          echo "Issue Title: $TITLE"
          echo "Issue Body: $BODY"
